### ISSUE TITLE
Inflating Error

### ISSUE THREAD

**Issue by ninbit** [DeKoServidoni/OMFM#17]
I did everything in the readme file but I get this error: "Error inflating class com.dekoservidoni.omfm.OneMoreFabMenu" How to resolve it? Full logcat:

E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.eightbit.tiphane, PID: 29893
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.eightbit.tiphane/com.eightbit.tiphane.MainActivity}: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.dekoservidoni.omfm.OneMoreFabMenu
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
at android.app.ActivityThread.-wrap14(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6682)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
Caused by: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.dekoservidoni.omfm.OneMoreFabMenu
Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class com.dekoservidoni.omfm.OneMoreFabMenu
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.newInstance0(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
at android.view.LayoutInflater.createView(LayoutInflater.java:652)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1011)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
at android.view.LayoutInflater.inflate(LayoutInflater.java:525)
at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
at android.view.LayoutInflater.inflate(LayoutInflater.java:378)
at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
at com.eightbit.tiphane.MainActivity.onCreate(MainActivity.java:37)
at android.app.Activity.performCreate(Activity.java:6942)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2880)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
at android.app.ActivityThread.-wrap14(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6682)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
at com.dekoservidoni.omfm.OneMoreFabMenu.<init>(OneMoreFabMenu.kt)
at com.dekoservidoni.omfm.OneMoreFabMenu.<init>(OneMoreFabMenu.kt:23)
at com.dekoservidoni.omfm.OneMoreFabMenu.<init>(OneMoreFabMenu.kt)
at java.lang.reflect.Constructor.newInstance0(Native Method) 
at java.lang.reflect.Constructor.newInstance(Constructor.java:430) 
at android.view.LayoutInflater.createView(LayoutInflater.java:652) 
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794) 
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734) 
at android.view.LayoutInflater.rInflate(LayoutInflater.java:865) 
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828) 
at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1011) 
at android.view.LayoutInflater.rInflate(LayoutInflater.java:861) 
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828) 
at android.view.LayoutInflater.inflate(LayoutInflater.java:525) 
at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
at android.view.LayoutInflater.inflate(LayoutInflater.java:378) 
at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
at com.eightbit.tiphane.MainActivity.onCreate(MainActivity.java:37) 
at android.app.Activity.performCreate(Activity.java:6942) 
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126) 
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2880) 
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988) 
at android.app.ActivityThread.-wrap14(ActivityThread.java) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:154) 
at android.app.ActivityThread.main(ActivityThread.java:6682) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410) 
E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.jvm.internal.Intrinsics" on path: DexPathList[[zip file "/data/app/com.eightbit.tiphane-1/base.apk", zip file "/data/app/com.eightbit.tiphane-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.eightbit.tiphane-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.eightbit.tiphane-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.eightbit.tiphane-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.eightbit.tiphane-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.eightbit.tiphane-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.eightbit.tiphane-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.eightbit.tiphane-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.eightbit.tiphane-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.eightbit.tiphane-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.eightbit.tiphane-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.eightbit.tiphane-1/lib/arm64, /system/lib64, /vendor/lib64]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
... 31 more

**Comment by DeKoServidoni** [comment]
Hello, how is your layout?
And, your project have kotlin support?

**Comment by ninbit** [comment]
I think my project doesn't have kotlin support because I started to write my app in Java long ago. Also I update Android Studio to 3.0.
I just used same example in my layout:
<com.dekoservidoni.omfm.OneMoreFabMenu
        android:id="@+id/fab"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom|end"
        app:content_options="@menu/omfm_content_options"
        app:close_on_click="true"
        app:color_main_button="@color/colorPrimaryDark"
        app:color_secondary_buttons="@color/colorPrimary"
        app:expanded_background_color="@color/omfm_expanded_background_sample"
        app:rotate_main_button="false"
        app:size_main_button="@integer/omfm_fab_size_normal"
        app:size_secondary_buttons="@integer/omfm_fab_size_mini"
        app:label_text_color="@color/colorPrimary"
        app:enable_main_as_action="true"
        app:main_action_drawable="@mipmap/ic_launcher"/>

**Comment by out386** [comment]
Top-level build.gradle:
`classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.1.51"`

Module build.gradle:
```
apply plugin: 'kotlin-android' 
apply plugin: 'kotlin-android-extensions'
```

```
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jre7:1.1.51"
```

**Comment by ninbit** [comment]
It's okay now! I think this reply should be added to readme file

**Comment by DeKoServidoni** [comment]
Sure, i will add. Thanks @out386 :)

**Comment by ParthThakar2012** [comment]
Hi there, 
I used your deme it's good and easy to use.
I want to change menu item text from MainActivity.kt file I did all posibilities is is there any function you created for this please let me know.
